Use latest version from https://github.com/maniackcrudelis/modele_ynh

diff --git a/scripts/fonctions b/scripts/fonctions
--- a/scripts/fonctions
+++ b/scripts/fonctions
@@ -1,27 +1,22 @@
 #!/bin/bash
 
-YNH_VERSION () {	# Renvoi le numéro de version de la moulinette Yunohost
-	ynh_version=$(sudo yunohost -v | grep "moulinette:" | cut -d' ' -f2 | cut -d'.' -f1,2)
-}
-
 CHECK_VAR () {	# Vérifie que la variable n'est pas vide.
 # $1 = Variable à vérifier
 # $2 = Texte à afficher en cas d'erreur
-	test -n "$1" || (echo "$2" && false)
+	test -n "$1" || (echo "$2" >&2 && false)
 }
 
 EXIT_PROPERLY () {	# Provoque l'arrêt du script en cas d'erreur. Et nettoye les résidus.
 	trap '' ERR
 	echo -e "\e[91m \e[1m"	# Shell in light red bold
-	echo -e "!!\n  $app install's script has encountered an error. Installation was cancelled.\n!!"
+	echo -e "!!\n  $app install's script has encountered an error. Installation was cancelled.\n!!" >&2
 
 	CLEAN_SETUP	# Appel la fonction de nettoyage spécifique du script install.
 
-	if [ $ynh_version = "2.2" ]; then
-		/bin/bash $script_dir/remove	# Appel le script remove. En 2.2, ce comportement n'est pas automatique.
-	fi
+	# Compense le bug de ssowat qui ne supprime pas l'entrée de l'app en cas d'erreur d'installation.
+	sudo sed -i "\@\"$domain$path/\":@d" /etc/ssowat/conf.json
 
-	exit 1
+	ynh_die
 }
 
 TRAP_ON () {	# Activate signal capture
@@ -37,7 +32,7 @@ TRAP_OFF () {	# Ignoring signal capture until TRAP_ON
 
 CHECK_USER () {	# Vérifie la validité de l'user admin
 # $1 = Variable de l'user admin.
-	sudo yunohost user list --json | grep -q "\"username\": \"$1\"" || (echo "Wrong admin" && false)
+	ynh_user_exists "$1" || (echo "Wrong admin" >&2 && false)
 }
 
 CHECK_PATH () {	# Vérifie la présence du / en début de path. Et son absence à la fin.
@@ -57,27 +52,29 @@ CHECK_FINALPATH () {	# Vérifie que le dossier de destination n'est pas déjà u
 	final_path=/var/www/$app
 	if [ -e "$final_path" ]
 	then
-		echo "This path already contains a folder"
+		echo "This path already contains a folder" >&2
 		false
 	fi
 }
 
 GENERATE_DB () {	# Créer une base de données et un utilisateur dédié au nom de l'app.
+# $1 = Nom de la base de donnée
+	db_user=$1
 	# Génère un mot de passe aléatoire.
-	db_pwd=$(head -n20 /dev/urandom | tr -c -d 'A-Za-z0-9' | head -c20)
+# 	db_pwd=$(head -n20 /dev/urandom | tr -c -d 'A-Za-z0-9' | head -c20)
+	db_pwd=$(ynh_string_random)
 	CHECK_VAR "$db_pwd" "db_pwd empty"
 	# Utilise '$app' comme nom d'utilisateur et de base de donnée
-	db_user=$app
 	# Initialise la base de donnée et stocke le mot de passe mysql.
 	ynh_mysql_create_db $db_user $db_user $db_pwd
-	sudo yunohost app setting $app mysqlpwd -v $db_pwd
+	ynh_app_setting_set $app mysqlpwd $db_pwd
 }
 
 SETUP_SOURCE () {	# Télécharge la source, décompresse et copie dans $final_path
 # $1 = Nom de l'archive téléchargée.
-	wget -nv --show-progress -i ../sources/source_url -O $1
+	wget -nv -i ../sources/source_url -O $1
 	# Vérifie la somme de contrôle de la source téléchargée.
-	md5sum -c ../sources/source_md5 --status || (echo "Corrupt source" && false)
+	md5sum -c ../sources/source_md5 --status || (echo "Corrupt source" >&2 && false)
 	# Décompresse la source
 	if [ "$(echo ${1##*.})" == "gz" ]; then
 		tar -x -f $1
@@ -89,12 +86,22 @@ SETUP_SOURCE () {	# Télécharge la source, décompresse et copie dans $final_pa
 	# Copie les fichiers sources
 	sudo cp -a $(cat ../sources/source_dir)/. "$final_path"
 	# Copie les fichiers additionnels ou modifiés.
-	sudo cp -a ../sources/ajouts/. "$final_path"
+	if test -e "../sources/ajouts"; then
+		sudo cp -a ../sources/ajouts/. "$final_path"
+	fi
+}
+
+ADD_SYS_USER () {   # Créer un utilisateur système dédié à l'app
+        if ! ynh_system_user_exists "$app"	# Test l'existence de l'utilisateur
+        then
+            sudo useradd -d /var/www/$app --system --user-group $app --shell /usr/sbin/nologin || (echo "Unable to create $app system account" >&2 && false)
+        fi
 }
 
 POOL_FPM () {	# Créer le fichier de configuration du pool php-fpm et le configure.
 	sed -i "s@__NAMETOCHANGE__@$app@g" ../conf/php-fpm.conf
 	sed -i "s@__FINALPATH__@$final_path@g" ../conf/php-fpm.conf
+	sed -i "s@__USER__@$app@g" ../conf/php-fpm.conf
 	finalphpconf=/etc/php5/fpm/pool.d/$app.conf
 	sudo cp ../conf/php-fpm.conf $finalphpconf
 	sudo chown root: $finalphpconf
@@ -107,13 +114,13 @@ POOL_FPM () {	# Créer le fichier de configuration du pool php-fpm et le configu
 STORE_MD5_CONFIG () {	# Enregistre la somme de contrôle du fichier de config
 # $1 = Nom du fichier de conf pour le stockage dans settings.yml
 # $2 = Nom complet et chemin du fichier de conf.
-	sudo yunohost app setting $app $1_file_md5 -v $(md5sum "$2" | cut -d' ' -f1)
+	ynh_app_setting_set $app $1_file_md5 $(sudo md5sum "$2" | cut -d' ' -f1)
 }
 
 CHECK_MD5_CONFIG () {	# Créé un backup du fichier de config si il a été modifié.
 # $1 = Nom du fichier de conf pour le stockage dans settings.yml
 # $2 = Nom complet et chemin du fichier de conf.
-	if [ "$(sudo yunohost app setting $app $1_file_md5)" != $(md5sum "$2" | cut -d' ' -f1) ]; then
+	if [ "$(ynh_app_setting_get $app $1_file_md5)" != $(sudo md5sum "$2" | cut -d' ' -f1) ]; then
 		sudo cp -a "$2" "$2.backup.$(date '+%d.%m.%y_%Hh%M,%Ss')"	# Si le fichier de config a été modifié, créer un backup.
 	fi
 }
@@ -157,22 +164,48 @@ REMOVE_LOGROTATE_CONF () {	# Suppression de la configuration de logrotate
 	fi
 }
 
-REMOVE_APP_DIR () {	# Suppression du dossier de l'application
-	if [ test -n "$app" ]
-	then	# Supprime le dossier seulement si $app n'est pas vide.
-		if [ -e "/var/www/$app" ]; then	# Delete final_path
-			echo "Delete app dir"
-			sudo rm -r "/var/www/$app"
+SECURE_REMOVE () {      # Suppression de dossier avec vérification des variables
+	chaine="$1"	# L'argument doit être donné entre quotes simple '', pour éviter d'interpréter les variables.
+	no_var=0
+	while (echo "$chaine" | grep -q '\$')	# Boucle tant qu'il y a des $ dans la chaine
+	do
+		no_var=1
+		global_var=$(echo "$chaine" | cut -d '$' -f 2)	# Isole la première variable trouvée.
+		only_var=\$$(expr "$global_var" : '\([A-Za-z0-9_]*\)')	# Isole complètement la variable en ajoutant le $ au début et en gardant uniquement le nom de la variable. Se débarrasse surtout du / et d'un éventuel chemin derrière.
+		real_var=$(eval "echo ${only_var}")		# `eval "echo ${var}` permet d'interpréter une variable contenue dans une variable.
+		if test -z "$real_var" || [ "$real_var" = "/" ]; then
+			echo "Variable $only_var is empty, suppression of $chaine cancelled." >&2
+			return 1
 		fi
+		chaine=$(echo "$chaine" | sed "s@$only_var@$real_var@")	# remplace la variable par sa valeur dans la chaine.
+	done
+	if [ "$no_var" -eq 1 ]
+	then
+		if [ -e "$chaine" ]; then
+			echo "Delete directory $chaine"
+			sudo rm -r "$chaine"
+		fi
+		return 0
+	else
+		echo "No detected variable." >&2
+		return 1
 	fi
 }
 
 REMOVE_BDD () {	# Suppression de la base de donnée et de l'utilisateur associé.
+# $1 = Nom de la base de donnée
 	# Utilise '$app' comme nom d'utilisateur et de base de donnée
-	db_user=$app
+	db_user=$1
 	if mysqlshow -u root -p$(sudo cat $MYSQL_ROOT_PWD_FILE) | grep -q "^| $db_user"; then
 		echo "Delete db"
 		ynh_mysql_drop_db $db_user
 		ynh_mysql_drop_user $db_user
 	fi
+}
+
+REMOVE_SYS_USER () {   # Supprime l'utilisateur système dédié à l'app
+    if ynh_system_user_exists "$app"	# Test l'existence de l'utilisateur
+    then
+    	sudo userdel $app
+    fi
 }
